apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-task-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/raj2410p/rajat_pandey_assessment
    targetRevision: HEAD
    path: infra/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-task-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
