apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: ai-task-platform
data:
  MONGO_URI: "mongodb://mongodb-service:27017/ai-task-platform"
  REDIS_URL: "redis://redis-service:6379"
  NODE_ENV: "production"

---
apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: ai-task-platform
type: Opaque
data:
  # Echo -n "supersecret" | base64
  JWT_SECRET: c3VwZXJzZWNyZXQ= 
